<?php
/**
 * Created by PhpStorm.
 * User: Gosia
 * Date: 2018-01-15
 * Time: 15:51
 */

namespace AppBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    public  function findAll()
    {
        $builder = $this->createQueryBuilder('p');
        $query = $builder->select('p')
            ->orderBy('p.dataComm', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}

